server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          default-label: ${GITHUB_LABEL}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost